// Runs CIFAD WASM analysis off the React main thread.
// Vite builds this as a module worker.

type WorkerRequest =
  | { type: 'init'; id: number }
  | { type: 'analyze'; id: number; file: File }
  | { type: 'cancel'; id: number; targetId: number };

type WorkerResponse =
  | { type: 'ready'; id: number }
  | { type: 'result'; id: number; result: any }
  | { type: 'error'; id: number; error: { message: string; stack?: string } };

// Cooperative-cancellation registry. The main thread posts `cancel` to mark an
// in-flight `analyze` request id as cancelled; the analyze loop checks this at
// every await boundary and throws a sentinel error. We cannot interrupt a
// synchronous WASM call mid-execution — for hard kills the main thread should
// `worker.terminate()` and respawn (the hook supports that path).
const cancelledIds = new Set<number>();
class CancelledError extends Error { constructor() { super('cancelled'); this.name = 'CancelledError'; } }
function throwIfCancelled(id: number) { if (cancelledIds.has(id)) throw new CancelledError(); }

let wasmMod: any | null = null;
let wasmInitPromise: Promise<void> | null = null;

async function ensureWasmReady() {
  if (wasmInitPromise) return wasmInitPromise;

  wasmInitPromise = (async () => {
    // @ts-ignore - generated by wasm-bindgen at build time
    const mod = await import('../../src-wasm/pkg/cifad_wasm');
    if (mod.default && typeof mod.default === 'function') {
      await mod.default();
    }
    wasmMod = mod;
  })();

  return wasmInitPromise;
}

function post(msg: WorkerResponse) {
  (self as any).postMessage(msg);
}

/** Autocorrelation lag spikes (Phase 12): lag 16 → AES block alignment; lag 8 → DES/3DES. */
function detectCryptoModeFromAutocorr(ac: number[]): 'AES-128/256' | 'DES/3DES' | null {
  if (!ac || ac.length < 17) return null;
  const spikeAt = (lag: number): boolean => {
    const v = Number(ac[lag]);
    if (!Number.isFinite(v)) return false;
    const nb: number[] = [];
    for (let d = -4; d <= 4; d++) {
      const i = lag + d;
      if (i >= 0 && i < ac.length && i !== lag) nb.push(Number(ac[i]));
    }
    const mean = nb.reduce((a, b) => a + b, 0) / Math.max(1, nb.length);
    return mean > 0 && v > mean * 2.15 && v > 0.085;
  };
  const s8 = spikeAt(8);
  const s16 = spikeAt(16);
  const v8 = Number(ac[8]);
  const v16 = Number(ac[16]);
  if (s16 && (!s8 || (Number.isFinite(v16) && Number.isFinite(v8) ? v16 >= v8 : s16))) return 'AES-128/256';
  if (s8) return 'DES/3DES';
  if (s16) return 'AES-128/256';
  return null;
}

/** HTTP/2 connection preface: "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n" */
const H2_MAGIC_PREAMBLE = new Uint8Array([
  0x50, 0x52, 0x49, 0x20, 0x2a, 0x20, 0x48, 0x54, 0x54, 0x50, 0x2f, 0x32, 0x2e, 0x30, 0x0d, 0x0a, 0x0d, 0x0a, 0x53, 0x4d, 0x0d, 0x0a, 0x0d, 0x0a
]);

/**
 * H1 / H2 / H3 heuristics from captured header bytes + global entropy map (after radar sampling).
 * Order: H2 (exact preface) → H1 (low entropy + HTTP/1 text) → H3 (high entropy + QUIC-ish first byte).
 */
function guessWebProtocol(headerBytes: Uint8Array, entropyMap: number[]): string | null {
  if (headerBytes.length >= H2_MAGIC_PREAMBLE.length) {
    let h2 = true;
    for (let i = 0; i < H2_MAGIC_PREAMBLE.length; i++) {
      if (headerBytes[i] !== H2_MAGIC_PREAMBLE[i]) {
        h2 = false;
        break;
      }
    }
    if (h2) return 'H2 (HTTP/2)';
  }

  const n = entropyMap.length;
  const avgEntropy = n > 0 ? entropyMap.reduce((a, b) => a + Number(b), 0) / n : 0;

  const scanLen = Math.min(2048, headerBytes.length);
  let prelude = '';
  if (scanLen > 0) {
    try {
      prelude = new TextDecoder('utf-8', { fatal: false }).decode(headerBytes.subarray(0, scanLen));
    } catch {
      prelude = '';
    }
  }
  const hasHttp11 = /HTTP\/1\.1/i.test(prelude);
  const hasGet = /\bGET\s/i.test(prelude);

  if (avgEntropy < 6.0 && (hasHttp11 || hasGet)) {
    return 'H1 (HTTP/1.1)';
  }

  if (avgEntropy > 7.5 && headerBytes.length > 0 && (headerBytes[0] & 0x40) === 0x40) {
    return 'H3 (QUIC)';
  }

  return null;
}

self.onmessage = async (evt: MessageEvent<WorkerRequest>) => {
  const data = evt.data;
  const id = data?.id ?? 0;

  try {
    if (data.type === 'init') {
      await ensureWasmReady();
      post({ type: 'ready', id });
      return;
    }

    if (data.type === 'cancel') {
      // Mark the targeted analyze request as cancelled. Eagerly notify the
      // client so it can short-circuit without waiting for the next checkpoint.
      cancelledIds.add(data.targetId);
      post({ type: 'error', id: data.targetId, error: { message: 'cancelled' } });
      return;
    }

    if (data.type === 'analyze') {
      await ensureWasmReady();
      throwIfCancelled(id);
      if (!wasmMod) throw new Error('WASM module not initialized');

      const file = data.file;
      const fileSize = file.size;

      const HEADER_BYTES = 1024 * 1024; // 1MB
      const FOOTER_BYTES = 64 * 1024;   // 64KB
      const RADAR_CHUNKS = 512;
      const SAMPLE_BYTES = 4 * 1024;    // 4KB

      const clamp = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n));

      const readSlice = async (start: number, end: number) => {
        throwIfCancelled(id);
        const s = clamp(start, 0, fileSize);
        const e = clamp(end, 0, fileSize);
        if (e <= s) return new Uint8Array();
        const buf = await file.slice(s, e).arrayBuffer();
        throwIfCancelled(id);
        return new Uint8Array(buf);
      };

      const shannonEntropy = (bytes: Uint8Array): number => {
        const len = bytes.length;
        if (len === 0) return 0;
        const counts = new Uint32Array(256);
        for (let i = 0; i < len; i++) counts[bytes[i]]++;
        let ent = 0;
        for (let i = 0; i < 256; i++) {
          const c = counts[i];
          if (c === 0) continue;
          const p = c / len;
          ent -= p * Math.log2(p);
        }
        return ent; // 0..8 for byte distributions
      };

      // --- 1) Header parse (telecom/crypto headers) ---
      const header = await readSlice(0, Math.min(HEADER_BYTES, fileSize));
      const trailing_artifacts: string[] = [];
      let parsed_structures: any[] = [];
      try {
        if (wasmMod.parse_file_structure) {
          const raw = wasmMod.parse_file_structure(header);
          if (Array.isArray(raw)) {
            parsed_structures = raw;
          } else if (raw && typeof raw === 'object') {
            if (Array.isArray((raw as any).nodes)) parsed_structures = (raw as any).nodes;
            const events = (raw as any).parse_events;
            if (Array.isArray(events)) {
              for (const ev of events) {
                if (typeof ev === 'string') trailing_artifacts.push(ev);
              }
            }
          }
        }
      } catch {
        parsed_structures = [];
      }

      let autocorrelation_graph: number[] = [];
      let header_signatures: string[] = [];
      try {
        const hdrAnalysis = wasmMod.analyze(header);
        const ac = hdrAnalysis?.autocorrelation_graph;
        if (Array.isArray(ac)) {
          autocorrelation_graph = ac.map((x: unknown) => Number(x));
        }
        const hs: unknown = hdrAnalysis?.signatures;
        if (Array.isArray(hs)) {
          header_signatures = hs.filter((s: unknown) => typeof s === 'string') as string[];
        }
      } catch {
        autocorrelation_graph = [];
        header_signatures = [];
      }

      // --- 2) Footer read (trailing signatures/footers) ---
      const footerStart = Math.max(0, fileSize - FOOTER_BYTES);
      const footer = await readSlice(footerStart, fileSize);

      const hasBytes = (hay: Uint8Array, needle: number[]) => {
        if (needle.length === 0) return true;
        outer: for (let i = 0; i <= hay.length - needle.length; i++) {
          for (let j = 0; j < needle.length; j++) {
            if (hay[i + j] !== needle[j]) continue outer;
          }
          return true;
        }
        return false;
      };

      // ZIP End of Central Directory: 50 4B 05 06
      if (hasBytes(footer, [0x50, 0x4b, 0x05, 0x06])) trailing_artifacts.push('ZIP_EOCD_TRAILER');

      // PKCS#7 SignedData OID: 1.2.840.113549.1.7.2
      // DER encoding commonly includes: 06 09 2A 86 48 86 F7 0D 01 07 02
      if (hasBytes(footer, [0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x07, 0x02])) {
        trailing_artifacts.push('PKCS7_SIGNEDDATA_OID');
      }

      // Run existing WASM signature detection on footer (small buffer => cheap).
      try {
        const footerResult = wasmMod.analyze(footer);
        const sigs: unknown = footerResult?.signatures;
        if (Array.isArray(sigs)) {
          for (const s of sigs) {
            if (typeof s === 'string') trailing_artifacts.push(`FOOTER_SIG_${s}`);
          }
        }
      } catch {
        // ignore footer analysis errors
      }

      // --- 3) Discrete sampling entropy for Radar ---
      const entropy_map: number[] = [];
      entropy_map.length = RADAR_CHUNKS;

      for (let i = 0; i < RADAR_CHUNKS; i++) {
        // Cancellation checkpoint: ensures user-aborted runs free CPU within
        // a single chunk's worth of work rather than scanning all 512 chunks.
        if ((i & 0x1f) === 0) throwIfCancelled(id);
        const chunkStart = Math.floor((i / RADAR_CHUNKS) * fileSize);
        const sample = await readSlice(chunkStart, chunkStart + SAMPLE_BYTES);
        entropy_map[i] = shannonEntropy(sample);
      }

      // Construct a 512x512 single-channel matrix where each row represents one discrete chunk.
      // Radar.tsx will expand this to RGBA for Deck.gl.
      const H = 512;
      const W = 512;
      const hilbert_matrix = new Uint8Array(W * H);
      for (let y = 0; y < H; y++) {
        const ent = entropy_map[y] ?? 0;
        const v = Math.max(0, Math.min(255, Math.round((ent / 8) * 255)));
        const rowOff = y * W;
        hilbert_matrix.fill(v, rowOff, rowOff + W);
      }

      const ENTROPY_HIGH = 6.2;
      const high_entropy_radar_indices = entropy_map
        .map((e, i) => (Number(e) >= ENTROPY_HIGH ? i : -1))
        .filter((i) => i >= 0);
      const crypto_mode = detectCryptoModeFromAutocorr(autocorrelation_graph);
      let protocol_guess = guessWebProtocol(header, entropy_map);
      // Promote vendor heuristic when web protocol is unknown.
      if (!protocol_guess && header_signatures.includes('VENDOR_PERIODIC_DETECTED')) {
        protocol_guess = 'VENDOR (Periodic / repeating header)';
      }

      for (const line of trailing_artifacts) {
        if (typeof line === 'string' && line.includes('Resync Event')) {
          console.info('[CIFAD worker]', line);
        }
      }

      throwIfCancelled(id);
      post({
        type: 'result',
        id,
        result: {
          entropy_map,
          hilbert_matrix,
          autocorrelation_graph,
          parsed_structures,
          trailing_artifacts,
          crypto_mode,
          high_entropy_radar_indices,
          protocol_guess
        }
      });

      return;
    }

    throw new Error(`Unknown worker message type: ${(data as any)?.type}`);
  } catch (e: any) {
    // If the request was cancelled, the cancel handler already notified the
    // client; avoid posting a duplicate error and just clean up the registry.
    if (cancelledIds.has(id)) {
      cancelledIds.delete(id);
      return;
    }
    post({
      type: 'error',
      id,
      error: { message: e?.message ?? String(e), stack: e?.stack }
    });
  }
};

