// Runs CIFAD WASM analysis off the React main thread.
// Vite builds this as a module worker.

type WorkerRequest =
  | { type: 'init'; id: number }
  | { type: 'analyze'; id: number; file: File };

type WorkerResponse =
  | { type: 'ready'; id: number }
  | { type: 'result'; id: number; result: any }
  | { type: 'error'; id: number; error: { message: string; stack?: string } };

let wasmMod: any | null = null;
let wasmInitPromise: Promise<void> | null = null;

async function ensureWasmReady() {
  if (wasmInitPromise) return wasmInitPromise;

  wasmInitPromise = (async () => {
    // @ts-ignore - generated by wasm-bindgen at build time
    const mod = await import('../../src-wasm/pkg/cifad_wasm');
    if (mod.default && typeof mod.default === 'function') {
      await mod.default();
    }
    wasmMod = mod;
  })();

  return wasmInitPromise;
}

function post(msg: WorkerResponse) {
  (self as any).postMessage(msg);
}

self.onmessage = async (evt: MessageEvent<WorkerRequest>) => {
  const data = evt.data;
  const id = data?.id ?? 0;

  try {
    if (data.type === 'init') {
      await ensureWasmReady();
      post({ type: 'ready', id });
      return;
    }

    if (data.type === 'analyze') {
      await ensureWasmReady();
      if (!wasmMod) throw new Error('WASM module not initialized');

      const file = data.file;
      const fileSize = file.size;

      const HEADER_BYTES = 1024 * 1024; // 1MB
      const FOOTER_BYTES = 64 * 1024;   // 64KB
      const RADAR_CHUNKS = 512;
      const SAMPLE_BYTES = 4 * 1024;    // 4KB

      const clamp = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n));

      const readSlice = async (start: number, end: number) => {
        const s = clamp(start, 0, fileSize);
        const e = clamp(end, 0, fileSize);
        if (e <= s) return new Uint8Array();
        const buf = await file.slice(s, e).arrayBuffer();
        return new Uint8Array(buf);
      };

      const shannonEntropy = (bytes: Uint8Array): number => {
        const len = bytes.length;
        if (len === 0) return 0;
        const counts = new Uint32Array(256);
        for (let i = 0; i < len; i++) counts[bytes[i]]++;
        let ent = 0;
        for (let i = 0; i < 256; i++) {
          const c = counts[i];
          if (c === 0) continue;
          const p = c / len;
          ent -= p * Math.log2(p);
        }
        return ent; // 0..8 for byte distributions
      };

      // --- 1) Header parse (telecom/crypto headers) ---
      const header = await readSlice(0, Math.min(HEADER_BYTES, fileSize));
      let parsed_structures: any[] = [];
      try {
        if (wasmMod.parse_file_structure) {
          parsed_structures = wasmMod.parse_file_structure(header);
        }
      } catch {
        parsed_structures = [];
      }

      // --- 2) Footer read (trailing signatures/footers) ---
      const footerStart = Math.max(0, fileSize - FOOTER_BYTES);
      const footer = await readSlice(footerStart, fileSize);

      const trailing_artifacts: string[] = [];

      const hasBytes = (hay: Uint8Array, needle: number[]) => {
        if (needle.length === 0) return true;
        outer: for (let i = 0; i <= hay.length - needle.length; i++) {
          for (let j = 0; j < needle.length; j++) {
            if (hay[i + j] !== needle[j]) continue outer;
          }
          return true;
        }
        return false;
      };

      // ZIP End of Central Directory: 50 4B 05 06
      if (hasBytes(footer, [0x50, 0x4b, 0x05, 0x06])) trailing_artifacts.push('ZIP_EOCD_TRAILER');

      // PKCS#7 SignedData OID: 1.2.840.113549.1.7.2
      // DER encoding commonly includes: 06 09 2A 86 48 86 F7 0D 01 07 02
      if (hasBytes(footer, [0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x07, 0x02])) {
        trailing_artifacts.push('PKCS7_SIGNEDDATA_OID');
      }

      // Run existing WASM signature detection on footer (small buffer => cheap).
      try {
        const footerResult = wasmMod.analyze(footer);
        const sigs: unknown = footerResult?.signatures;
        if (Array.isArray(sigs)) {
          for (const s of sigs) {
            if (typeof s === 'string') trailing_artifacts.push(`FOOTER_SIG_${s}`);
          }
        }
      } catch {
        // ignore footer analysis errors
      }

      // --- 3) Discrete sampling entropy for Radar ---
      const entropy_map: number[] = [];
      entropy_map.length = RADAR_CHUNKS;

      for (let i = 0; i < RADAR_CHUNKS; i++) {
        const chunkStart = Math.floor((i / RADAR_CHUNKS) * fileSize);
        const sample = await readSlice(chunkStart, chunkStart + SAMPLE_BYTES);
        entropy_map[i] = shannonEntropy(sample);
      }

      // Construct a 512x512 single-channel matrix where each row represents one discrete chunk.
      // Radar.tsx will expand this to RGBA for Deck.gl.
      const H = 512;
      const W = 512;
      const hilbert_matrix = new Uint8Array(W * H);
      for (let y = 0; y < H; y++) {
        const ent = entropy_map[y] ?? 0;
        const v = Math.max(0, Math.min(255, Math.round((ent / 8) * 255)));
        const rowOff = y * W;
        hilbert_matrix.fill(v, rowOff, rowOff + W);
      }

      post({
        type: 'result',
        id,
        result: {
          entropy_map,
          hilbert_matrix,
          autocorrelation_graph: [],
          parsed_structures,
          trailing_artifacts
        }
      });

      return;
    }

    throw new Error(`Unknown worker message type: ${(data as any)?.type}`);
  } catch (e: any) {
    post({
      type: 'error',
      id,
      error: { message: e?.message ?? String(e), stack: e?.stack }
    });
  }
};

